const PRODUCTS = [

  // ── CP PLUS NETWORK CAMERAS ──────────────────────
  {
    id: 1,
    name: "CP-UNC-TA41L3C-D-LQ2",
    brand: "CP Plus",
    category: "outdoor",
    tag: "Dual Light",
    tagColor: "#e53935",
    subtitle: "4MP Dual Light Bullet Camera – 30Mtr.",
    image: "cp_bullet_dual.png",
    images: ["cp_bullet_dual.png", "cp_bullet_full.png", "cp_guard_bullet.png"],
    shortDesc: "4MP Dual Light IP Bullet — IR + Warm Light, Built-in Mic, PoE, IP67.",
    description: "The CP-UNC-TA41L3C-D-LQ2 is a 4MP Dual Light Network Bullet Camera with both IR and warm white light for color night vision. Features built-in microphone, 120dB WDR, and PoE power. Ideal for outdoor perimeter surveillance with clear color footage even in complete darkness.",
    highlights: ["4MP PS CMOS – 2688x1520", "IR + Warm Dual Light 30m", "Built-in Microphone", "120dB WDR", "PoE + IP67", "H.265 Compression"],
    specs: [
      { label: "Model", value: "CP-UNC-TA41L3C-D-LQ2" },
      { label: "Image Sensor", value: "1/2.9 inch 4MP PS CMOS" },
      { label: "Max. Resolution", value: "2688 x 1520 / 2560 x 1440 @25fps" },
      { label: "Video Compression", value: "H.265, H.264, H.264H, H.264B, MJPEG" },
      { label: "Stream", value: "Triple Stream Support" },
      { label: "WDR", value: "120dB" },
      { label: "Features", value: "Day/Night ICR, 3D NR, ROI, AWB, AGC, BLC, HLC" },
      { label: "Audio", value: "Built-in Microphone" },
      { label: "Lens", value: "3.6mm Fixed" },
      { label: "IR Range", value: "30 Mtrs." },
      { label: "Warm Light", value: "30 Mtrs." },
      { label: "Power", value: "PoE (IEEE 802.3af)" },
      { label: "Weatherproof", value: "IP67" },
      { label: "Mobile App", value: "iCMOB, gCMOB" },
      { label: "CMS", value: "KVMS Pro Lite, EVMS Pro" }
    ],
    inBox: ["1x Bullet Camera", "Mounting Bracket", "Screws", "User Manual", "Warranty Card"]
  },
  {
    id: 2,
    name: "CP-UNC-DA21L3C-Q",
    brand: "CP Plus",
    category: "indoor",
    tag: "IP Dome",
    tagColor: "#1565c0",
    subtitle: "2MP Network IR Dome Camera – 30Mtr.",
    image: "cp_dome_ir.png",
    images: ["cp_dome_ir.png", "cp_vandal_dome1.png", "cp_vandal_dome2.png"],
    shortDesc: "2MP IP Dome — Instastream H.265, Built-in Mic, PoE, IP67, 30m IR.",
    description: "The CP-UNC-DA21L3C-Q is a compact 2MP Network IR Dome Camera with built-in microphone and Instastream technology for smooth remote viewing. With DWDR, 3D NR, and digital watermarking, it delivers reliable 24/7 surveillance for indoor and outdoor installations.",
    highlights: ["2MP PS CMOS – 1920x1080", "Built-in Microphone", "Instastream Technology", "DWDR + 3D NR", "IR Range 30m, PoE, IP67", "Digital Watermarking"],
    specs: [
      { label: "Model", value: "CP-UNC-DA21L3C-Q" },
      { label: "Image Sensor", value: "1/2.8 inch 2MP PS CMOS" },
      { label: "Max. Resolution", value: "1920 x 1080 @25/30fps" },
      { label: "Video Compression", value: "Instastream, H.265, H.264, MJPEG" },
      { label: "Stream", value: "Triple Stream Support" },
      { label: "Audio", value: "Built-in Microphone" },
      { label: "Lens", value: "3.6mm (2.8mm optional)" },
      { label: "Features", value: "DWDR, Day/Night ICR, 3D NR, ROI, AWB, AGC, BLC, HLC" },
      { label: "IR Range", value: "30 Mtrs." },
      { label: "Power", value: "PoE (IEEE 802.3af)" },
      { label: "Weatherproof", value: "IP67" },
      { label: "Special", value: "Digital Watermarking" }
    ],
    inBox: ["1x Dome Camera", "Mounting Template", "Screws", "User Manual", "Warranty Card"]
  },
  {
    id: 3,
    name: "CP-UNC-VC81ZL5C-VMD-Q",
    brand: "CP Plus",
    category: "indoor",
    tag: "8MP 4K",
    tagColor: "#6d4c41",
    subtitle: "8MP Network IR Vandal Dome Camera – 50Mtr.",
    image: "cp_vandal_dome1.png",
    images: ["cp_vandal_dome1.png", "cp_vandal_dome2.png", "cp_dome_ir.png"],
    shortDesc: "8MP 4K Vandal Dome — Motorized Lens, Starlight, IP67, IK10, SD Card.",
    description: "The CP-UNC-VC81ZL5C-VMD-Q is a premium 8MP 4K Vandal Dome Camera with motorized varifocal lens for flexible coverage adjustment. Features Starlight Technology for ultra-low light performance, 120dB WDR, and IK10 vandal-resistant housing. Supports onboard MicroSD storage and PoE power.",
    highlights: ["8MP 4K – 3840x2160", "2.7-13.5mm Motorized Lens", "Starlight Technology", "120dB WDR", "IP67 + IK10 Vandal Proof", "MicroSD + PoE"],
    specs: [
      { label: "Model", value: "CP-UNC-VC81ZL5C-VMD-Q" },
      { label: "Image Sensor", value: "1/2.7 inch 8MP PS CMOS" },
      { label: "Max. Resolution", value: "3840 x 2160 @20fps" },
      { label: "Video Compression", value: "Instastream, H.265, H.264, MJPEG" },
      { label: "Stream", value: "Quad Stream Support" },
      { label: "Lens", value: "2.7mm–13.5mm Motorized Varifocal" },
      { label: "WDR", value: "120dB" },
      { label: "Features", value: "Day/Night ICR, 2D/3D NR, ROI, BLC, HLC, AWB, AGC" },
      { label: "Special", value: "Starlight Technology" },
      { label: "IR Range", value: "50 Mtrs." },
      { label: "Storage", value: "Micro SD Card" },
      { label: "Weatherproof", value: "IP67" },
      { label: "Vandal Proof", value: "IK10" },
      { label: "Power", value: "PoE" }
    ],
    inBox: ["1x Vandal Dome Camera", "Mounting Template", "Screws", "User Manual", "Warranty Card"]
  },
  {
    id: 4,
    name: "CP-GPC-LT24L3",
    brand: "CP Plus",
    category: "outdoor",
    tag: "Guard+",
    tagColor: "#2e7d32",
    subtitle: "2.4MP Full Color Guard+ Bullet Camera",
    image: "cp_guard_bullet.png",
    images: ["cp_guard_bullet.png", "cp_bullet_dual.png", "cp_bullet_full.png"],
    shortDesc: "2.4MP Full Color Guard+ Bullet — IP66, IR 30m, OSD Menu support.",
    description: "The CP-GPC-LT24L3 is a 2.4MP Full Color Guard+ Bullet Camera from the CP Plus Guard+ series. Delivers vivid full-color footage in all lighting conditions with 30m IR range. Features DWDR, 3D-NR, and OSD menu for easy on-site configuration. IP66 rated for outdoor use.",
    highlights: ["2.4MP Full Color", "IR Range 30m", "DWDR + 3D-NR", "IP66 Weatherproof", "OSD Menu", "Guard+ Series"],
    specs: [
      { label: "Model", value: "CP-GPC-LT24L3" },
      { label: "Series", value: "Guard+" },
      { label: "Image Sensor", value: "1/3 inch 2.4MP PS CMOS" },
      { label: "Max. Resolution", value: "2.4MP @25/30fps" },
      { label: "Lens", value: "3.6mm Fixed" },
      { label: "Features", value: "DWDR, 3D-NR, AWB, AGC" },
      { label: "IR Range", value: "Up to 30 Mtrs." },
      { label: "OSD Menu", value: "Supported" },
      { label: "Weatherproof", value: "IP66" }
    ],
    inBox: ["1x Bullet Camera", "Mounting Bracket", "Screws", "User Manual", "Warranty Card"]
  },
  {
    id: 5,
    name: "CP-UNC-TA21L3C-Q",
    brand: "CP Plus",
    category: "outdoor",
    tag: "IP Camera",
    tagColor: "#1565c0",
    subtitle: "2MP Network IR Bullet Camera – 30Mtr.",
    image: "cp_bullet_full.png",
    images: ["cp_bullet_full.png", "cp_bullet_dual.png", "cp_guard_bullet.png"],
    shortDesc: "2MP IP Bullet — H.265, Built-in Mic, PoE, IP67, IR 30m.",
    description: "The CP-UNC-TA21L3C-Q is a 2MP Network IR Bullet Camera with built-in microphone and Instastream technology. With DWDR, 3D NR, and PoE support, it delivers reliable outdoor surveillance with 30m IR night vision.",
    highlights: ["2MP PS CMOS – 1920x1080", "Built-in Microphone", "IR Night Vision 30m", "DWDR + 3D NR", "PoE + IP67", "H.265 Compression"],
    specs: [
      { label: "Model", value: "CP-UNC-TA21L3C-Q" },
      { label: "Image Sensor", value: "1/2.8 inch 2MP PS CMOS" },
      { label: "Max. Resolution", value: "1920 x 1080 @25/30fps" },
      { label: "Video Compression", value: "Instastream, H.265, H.264, MJPEG" },
      { label: "Stream", value: "Triple Stream Support" },
      { label: "Audio", value: "Built-in Microphone" },
      { label: "Lens", value: "3.6mm Fixed" },
      { label: "IR Range", value: "30 Mtrs." },
      { label: "Features", value: "DWDR, Day/Night ICR, 3D NR, ROI, AWB, AGC, BLC, HLC" },
      { label: "Power", value: "PoE (IEEE 802.3af)" },
      { label: "Weatherproof", value: "IP67" }
    ],
    inBox: ["1x Bullet Camera", "Mounting Bracket", "Screws", "User Manual", "Warranty Card"]
  },

  // ── WIFI / SMART CAMERAS ─────────────────────────
  {
    id: 6,
    name: "EZ-R33T",
    brand: "CP Plus",
    category: "wifi",
    tag: "4G Camera",
    tagColor: "#0288d1",
    subtitle: "3MP 4G Smart Camera – Google Home Compatible",
    image: "wifi_outdoor.png",
    images: ["wifi_outdoor.png", "cp_bullet_dual.png", "router_4g.png"],
    shortDesc: "3MP 4G Camera — IR+White LED, Google Home, Works anywhere without WiFi.",
    description: "The EZ-R33T is a 3MP 4G Smart Camera that works without WiFi using a SIM card. Compatible with Google Home for smart home integration. Features dual illumination with both IR and white LED, H.265 compression, and works up to 30m at night.",
    highlights: ["3MP CMOS Sensor", "4G SIM Support – No WiFi Needed", "Google Home Compatible", "IR + White LED 20-30m", "H.265 Compression", "Max 15fps @3MP"],
    specs: [
      { label: "Model", value: "EZ-R33T" },
      { label: "Image Sensor", value: "1/3 inch 3MP CMOS" },
      { label: "Lens", value: "4mm Fixed" },
      { label: "Video Compression", value: "H.265" },
      { label: "Connectivity", value: "4G SIM Card Support" },
      { label: "Smart Home", value: "Works with Google Home" },
      { label: "Frame Rate", value: "Max. 15fps @3MP" },
      { label: "IR Distance", value: "20–30 Mtrs." },
      { label: "White LED", value: "15–20 Mtrs." }
    ],
    inBox: ["1x 4G Camera", "Power Adapter", "Mounting Bracket", "User Manual"]
  },
  {
    id: 7,
    name: "Godrej Eve Pro 3 Pan Tilt",
    brand: "Godrej",
    category: "wifi",
    tag: "Pan Tilt",
    tagColor: "#37474f",
    subtitle: "3MP Smart WiFi PT Camera – 350° Pan, Google Home",
    image: "godrej_pantilt.png",
    images: ["godrej_pantilt.png", "godrej_outdoor_ptz.png", "wifi_outdoor.png"],
    shortDesc: "Godrej 3MP Pan-Tilt WiFi Camera — 350° rotation, Google Home, Night Vision.",
    description: "The Godrej Eve Pro 3 Pan Tilt is a smart indoor WiFi security camera with 350-degree pan rotation for complete room coverage. Compatible with Google Home and Alexa. Features color night vision, two-way talk, and motion detection alerts on your smartphone.",
    highlights: ["3MP Full HD Resolution", "350° Pan / Tilt Coverage", "Google Home Compatible", "Color Night Vision", "Two-Way Audio", "Motion Detection Alerts"],
    specs: [
      { label: "Model", value: "Godrej Eve Pro 3 Pan Tilt" },
      { label: "Brand", value: "Godrej" },
      { label: "Resolution", value: "3MP Full HD" },
      { label: "Pan Angle", value: "350 Degrees" },
      { label: "Connectivity", value: "WiFi" },
      { label: "Smart Home", value: "Google Home / Alexa Compatible" },
      { label: "Night Vision", value: "Color Night Vision" },
      { label: "Audio", value: "Two-Way Talk" },
      { label: "Alerts", value: "Motion Detection Push Notifications" }
    ],
    inBox: ["1x Pan Tilt Camera", "Mounting Plate", "Power Adapter", "KA M 4X35MM Screw", "USB Cable", "User Manual"]
  },
  {
    id: 8,
    name: "Godrej Eve Pro 4G Mini-PT",
    brand: "Godrej",
    category: "wifi",
    tag: "4G PT Cam",
    tagColor: "#37474f",
    subtitle: "4G Outdoor Pan-Tilt WiFi Security Camera",
    image: "godrej_outdoor_ptz.png",
    images: ["godrej_outdoor_ptz.png", "godrej_pantilt.png", "wifi_outdoor.png"],
    shortDesc: "Godrej 4G Outdoor PT Camera — Works without WiFi, Pan-Tilt, Night Vision.",
    description: "The Godrej Eve Pro 4G Mini-PT is a rugged outdoor pan-tilt camera that works with a 4G SIM card — no WiFi required. Perfect for farms, remote locations, and outdoor monitoring. Features full pan-tilt movement, color night vision, and live viewing on your smartphone from anywhere.",
    highlights: ["4G SIM – No WiFi Needed", "Outdoor Pan-Tilt", "Color Night Vision", "Live View on Phone", "Weatherproof Design", "Two-Way Audio"],
    specs: [
      { label: "Model", value: "Godrej Eve Pro 4G Mini-PT" },
      { label: "Brand", value: "Godrej" },
      { label: "Connectivity", value: "4G SIM Card" },
      { label: "Type", value: "Outdoor Pan-Tilt Camera" },
      { label: "Night Vision", value: "Color Night Vision" },
      { label: "Audio", value: "Two-Way Talk" },
      { label: "Installation", value: "Outdoor Wall Mount" },
      { label: "App", value: "Godrej Smart Security App" }
    ],
    inBox: ["1x 4G PT Camera", "Wall Mounting Bracket", "Power Adapter", "User Manual"]
  },

  // ── DASHCAMS ─────────────────────────────────────
  {
    id: 9,
    name: "CP-KH27B",
    brand: "CP Plus",
    category: "dashcam",
    tag: "CarKam 4G",
    tagColor: "#b71c1c",
    subtitle: "CarKam 4G 2MP with Rear Camera & Hardwire Kit",
    image: "carkam_4g.png",
    images: ["carkam_4g.png", "carkam_3mp.png", "carkam_4g.png"],
    shortDesc: "CarKam 4G Dashcam — GPS, Two-way Talk, Rear Camera, Parking Mode.",
    description: "The CP-KH27B CarKam is a professional 4G dashcam with front and rear cameras. Built-in GPS for live tracking, G-sensor for emergency recording, and 4G/5G SIM support for live streaming. Perfect for fleet management and personal vehicle security.",
    highlights: ["2MP Front + Rear Camera", "4G/5G SIM Support", "Built-in GPS Tracking", "G-Sensor Emergency Recording", "Two-Way Talk", "H.265 Compression"],
    specs: [
      { label: "Model", value: "CP-KH27B" },
      { label: "Series", value: "CarKam" },
      { label: "Resolution", value: "2MP" },
      { label: "Cameras", value: "Front + Rear Camera" },
      { label: "Connectivity", value: "4G/5G SIM Support" },
      { label: "GPS", value: "Built-in GPS" },
      { label: "Audio", value: "Two-Way Talk" },
      { label: "G-Sensor", value: "Yes – Emergency Recording" },
      { label: "Video Compression", value: "H.265" },
      { label: "Special", value: "Time Lapse, Parking Mode" },
      { label: "Power", value: "Hardwire Kit Included" }
    ],
    inBox: ["1x Front Dashcam", "1x Rear Camera", "Hardwire Kit", "Mounting Accessories", "User Manual"]
  },
  {
    id: 10,
    name: "CP-KW310",
    brand: "CP Plus",
    category: "dashcam",
    tag: "CarKam 3MP",
    tagColor: "#b71c1c",
    subtitle: "CarKam 3MP Dashcam with Hardwire Kit",
    image: "carkam_3mp.png",
    images: ["carkam_3mp.png", "carkam_4g.png", "carkam_3mp.png"],
    shortDesc: "CarKam 3MP Dashcam — 1TB SD support, 24/7 Parking Monitor, G-Sensor.",
    description: "The CP-KW310 CarKam is a 3MP dashcam with support for SD cards up to 1TB, making it ideal for long-trip recording. Features G-sensor for automatic emergency recording, 24/7 parking monitoring, and time lapse mode. Hardwire kit included for clean installation.",
    highlights: ["3MP Resolution", "SD Card up to 1TB (U3)", "24/7 Parking Monitoring", "G-Sensor Emergency Recording", "Time Lapse Mode", "Hardwire Kit Included"],
    specs: [
      { label: "Model", value: "CP-KW310" },
      { label: "Series", value: "CarKam" },
      { label: "Resolution", value: "3MP" },
      { label: "Storage", value: "SD Card up to 1TB (Class 10 U3)" },
      { label: "G-Sensor", value: "Yes – Emergency Recording" },
      { label: "Parking Mode", value: "24/7 Parking Monitoring" },
      { label: "Special", value: "Time Lapse" },
      { label: "Power", value: "Hardwire Kit Included" }
    ],
    inBox: ["1x Dashcam", "Hardwire Kit", "Mounting Adhesive", "User Manual"]
  },

  // ── ACCESSORIES ──────────────────────────────────
  {
    id: 11,
    name: "CP-UM256W",
    brand: "CP Plus",
    category: "accessories",
    tag: "Memory Card",
    tagColor: "#c62828",
    subtitle: "256GB Wide Temp Micro SD Card – V30, A2, U3",
    image: "sdcard_256w.png",
    images: ["sdcard_256w.png", "sdcard_256w.png", "sdcard_256w.png"],
    shortDesc: "256GB Wide Temp SD — V30/A2/U3, extreme temperature, 4 types protection.",
    description: "The CP-UM256W is a 256GB Wide Temperature Micro SD card for surveillance cameras in extreme environments. Rated V30, A2, C10, U3 for high-speed HD recording. Wide temperature range makes it perfect for outdoor cameras in harsh Indian weather conditions.",
    highlights: ["256GB High Capacity", "Wide Temperature Range", "Speed: C10/U3/V30/A2", "4 Types of Protection", "24/7 Surveillance Optimized", "Extreme Weather Resistant"],
    specs: [
      { label: "Model", value: "CP-UM256W" },
      { label: "Capacity", value: "256GB" },
      { label: "Speed Class", value: "UHS-I C10 / U3 / V30 / A2" },
      { label: "Special", value: "Wide Temperature" },
      { label: "Form Factor", value: "MicroSD (microSDXC)" },
      { label: "Protection", value: "4 Types of Protection" },
      { label: "Compatibility", value: "All cameras, DVRs, NVRs, smartphones" }
    ],
    inBox: ["1x Micro SD Card", "Warranty Card"]
  },
  {
    id: 12,
    name: "CP-XR-DE41-S-V2",
    brand: "CP Plus",
    category: "accessories",
    tag: "4G Router",
    tagColor: "#1565c0",
    subtitle: "4G WiFi Router – LTE, WiFi 6, Quad Antenna",
    image: "router_4g.png",
    images: ["router_4g.png", "switch_8port.png", "router_4g.png"],
    shortDesc: "CP Plus 4G Router — FDD/TDD-LTE, WiFi 6, WPS, External Antenna.",
    description: "The CP-XR-DE41-S-V2 is a 4G WiFi Router supporting FDD-LTE, TDD-LTE, and WCDMA networks. With WiFi 6 support, 2.4GHz band, and external quad antenna for strong signal. Ideal for IP camera installations in locations without broadband internet.",
    highlights: ["4G LTE – FDD + TDD", "WiFi 6 Support", "2.4GHz WiFi Band", "External Quad Antenna", "WPS + Reset Button", "Plug & Play Setup"],
    specs: [
      { label: "Model", value: "CP-XR-DE41-S-V2" },
      { label: "Network", value: "FDD-LTE, TDD-LTE, WCDMA" },
      { label: "WiFi", value: "2.4GHz, WiFi 6" },
      { label: "Antenna", value: "External Antenna Support" },
      { label: "Buttons", value: "Reset, WPS Button" },
      { label: "Use Case", value: "IP Cameras, Remote Surveillance" }
    ],
    inBox: ["1x 4G Router", "Power Adapter", "User Manual"]
  },
  {
    id: 13,
    name: "CP-SL06K",
    brand: "CP Plus",
    category: "accessories",
    tag: "Solar Kit",
    tagColor: "#f57f17",
    subtitle: "Solar Panel Kit with Built-in Battery – 30W, 12Hr Backup",
    image: "solar_panel.png",
    images: ["solar_panel.png", "solar_panel.png", "wifi_outdoor.png"],
    shortDesc: "30W Solar Kit — 12hr backup, 76.8Wh battery, for outdoor cameras.",
    description: "The CP-SL06K is a 30W Solar Panel Kit with built-in battery backup for powering outdoor cameras and security systems in locations without electricity. Provides 12 hours backup with 76.8Wh battery capacity. LED indicators for charging status monitoring.",
    highlights: ["30W Maximum Power Output", "12 Hours Battery Backup", "76.8Wh Battery Capacity", "LED Charging Indicators", "Pole Mount Design", "No Electricity Needed"],
    specs: [
      { label: "Model", value: "CP-SL06K" },
      { label: "Max Power", value: "30W" },
      { label: "Battery Capacity", value: "76.8Wh" },
      { label: "Backup Time", value: "12 Hours (at 5.5W load)" },
      { label: "LED – Charging", value: "Green Blink" },
      { label: "LED – Full Charge", value: "Green ON" },
      { label: "LED – Discharge", value: "Red ON" },
      { label: "Mount", value: "Pole Mount with Bracket" }
    ],
    inBox: ["1x Solar Panel", "Mounting Bracket", "Screws & Bolts", "User Manual"]
  },

  // ── VIDEO INTERCOM ───────────────────────────────
  {
    id: 14,
    name: "CP-UVK-701MTA",
    brand: "CP Plus",
    category: "accessories",
    tag: "Video Intercom",
    tagColor: "#4a148c",
    subtitle: "7 inch Video Intercom Kit with Memory – TFT Screen",
    image: "video_intercom.png",
    images: ["video_intercom.png", "video_intercom.png", "cp_dome_ir.png"],
    shortDesc: "7 inch Video Intercom — Unlock, Voice/Video Call, 200 Snapshots Memory.",
    description: "The CP-UVK-701MTA is a complete video intercom kit with a 7-inch TFT screen indoor monitor and outdoor door station. Supports unlock function, voice call, video call, volume adjustment, and doorway monitoring. System capacity supports 2 door stations and 3 indoor monitors with in-built memory for 200 snapshots.",
    highlights: ["7 inch TFT Color Screen", "Unlock + Video + Voice Call", "In-Built Memory – 200 Snapshots", "DWDR Technology", "2 Door + 3 Indoor Monitors", "Multiple Bell Sounds"],
    specs: [
      { label: "Model", value: "CP-UVK-701MTA" },
      { label: "Screen", value: "7 inch TFT (17.78cm)" },
      { label: "Functions", value: "Unlock, Voice Call, Video Call, Volume, Monitor" },
      { label: "System Capacity", value: "2 Door Stations + 3 Indoor Monitors" },
      { label: "Memory", value: "In-Built (200 Snapshots)" },
      { label: "WDR", value: "DWDR Supported" },
      { label: "Bell Sounds", value: "Multiple Options" }
    ],
    inBox: ["1x Indoor Monitor (7 inch)", "1x Outdoor Door Station", "Mounting Hardware", "User Manual", "Warranty Card"]
  },

  // ── SWITCHES ─────────────────────────────────────
  {
    id: 15,
    name: "CP-UNW-HPU8H2-96",
    brand: "CP Plus",
    category: "switch",
    tag: "PoE Switch",
    tagColor: "#1565c0",
    subtitle: "10 Port Switch – 8 PoE + 2 Uplink Ports, 96W",
    image: "switch_8port.png",
    images: ["switch_8port.png", "switch_16port.png", "switch_4port.png"],
    shortDesc: "10 Port PoE Switch — 8 PoE ports, 96W total, 250m range, Plug & Play.",
    description: "The CP-UNW-HPU8H2-96 is a 10-port PoE switch with 8 PoE-enabled ports and 2 uplink ports. Supports 250m extended transmission at 10Mbps and is completely plug-and-play — perfect for IP camera installations.",
    highlights: ["8 PoE Ports", "2 Uplink Ports", "96W Total PoE Budget", "250m Extended Range", "IEEE 802.3af/at", "Plug & Play"],
    specs: [
      { label: "Model", value: "CP-UNW-HPU8H2-96" },
      { label: "Total Ports", value: "10 Ports" },
      { label: "PoE Ports", value: "Port 1–8: 10/100 Mbps PoE" },
      { label: "Uplink Ports", value: "Port 9–10: 10/100 Mbps" },
      { label: "PoE Budget", value: "96W Total" },
      { label: "Transmission", value: "Up to 250 Mtr. (10 Mbps)" },
      { label: "Standards", value: "IEEE802.3, 802.3u, 802.3x" },
      { label: "Install", value: "Wall-mount / Desktop / Plug-and-play" }
    ],
    inBox: ["1x PoE Switch", "Power Adapter", "Mounting Screws", "User Manual"]
  },
  {
    id: 16,
    name: "CP-DNW-HPU16G2F1-200",
    brand: "CP Plus",
    category: "switch",
    tag: "PoE Switch",
    tagColor: "#1565c0",
    subtitle: "19 Port Switch – 16 PoE + 2 Gigabit + 1 SFP",
    image: "switch_16port.png",
    images: ["switch_16port.png", "switch_8port.png", "switch_4port.png"],
    shortDesc: "19 Port Managed PoE — 16 PoE 30W each, 2 Gigabit, 1 SFP, ESD Protection.",
    description: "Professional 19-port PoE switch with 16 PoE ports at 30W each, 2 Gigabit uplinks, and 1 SFP fibre port. ESD and surge protection for 24/7 reliability. Supports 250m extended transmission.",
    highlights: ["16 PoE Ports – 30W Each", "2 Gigabit Uplinks", "1 SFP Fibre Port", "250m Extended Range", "ESD + Surge Protection", "Kensington Security Slot"],
    specs: [
      { label: "Model", value: "CP-DNW-HPU16G2F1-200" },
      { label: "Total Ports", value: "19 Ports" },
      { label: "PoE Ports", value: "16x 10/100 Mbps, 30W each" },
      { label: "Uplink", value: "2x Gigabit + 1x SFP" },
      { label: "Transmission", value: "Up to 250 Mtr." },
      { label: "Protection", value: "ESD + Surge Protection" },
      { label: "Standards", value: "IEEE802.3/802.3u/802.3ab/802.3z" }
    ],
    inBox: ["1x PoE Switch", "Power Adapter", "Rack Mount Kit", "User Manual"]
  },
  {
    id: 17,
    name: "CP-UNW-HPU4H2-48",
    brand: "CP Plus",
    category: "switch",
    tag: "PoE Switch",
    tagColor: "#1565c0",
    subtitle: "6 Port Switch – 4 PoE + 2 Uplink Ports, 48W",
    image: "switch_4port.png",
    images: ["switch_4port.png", "switch_8port.png", "switch_16port.png"],
    shortDesc: "6 Port PoE Switch — 4 PoE ports, 250m range, compact desktop design.",
    description: "Compact 6-port PoE switch with 4 PoE-enabled ports for small IP camera setups. Supports 250m extended transmission and is completely plug-and-play. Ideal for homes and small offices.",
    highlights: ["4 PoE Ports", "2 Uplink Ports", "48W PoE Budget", "250m Extended Range", "Compact Design", "Plug & Play"],
    specs: [
      { label: "Model", value: "CP-UNW-HPU4H2-48" },
      { label: "Total Ports", value: "6 Ports" },
      { label: "PoE Ports", value: "Port 1–4: 10/100 Mbps PoE" },
      { label: "Uplink", value: "Port 5–6: 10/100 Mbps" },
      { label: "PoE Budget", value: "48W Total" },
      { label: "Transmission", value: "Up to 250 Mtr." },
      { label: "Install", value: "Wall-mount / Desktop / Plug-and-play" }
    ],
    inBox: ["1x PoE Switch", "Power Adapter", "Mounting Screws", "User Manual"]
  },

  // ── BODY CAMERAS ─────────────────────────────────
  {
    id: 18,
    name: "CP-EBK-1073-K",
    brand: "CP Plus",
    category: "bodycam",
    tag: "Body Cam Kit",
    tagColor: "#37474f",
    subtitle: "2K Body Worn Camera Kit with Docking Station",
    image: "bodycam_kit.png",
    images: ["bodycam_kit.png", "bodycam_4mp.png", "docking_station.png"],
    shortDesc: "2K Body Cam — 4G Live, WiFi Upload, GPS Tracking, 128GB Built-in.",
    description: "Professional 2K Body Worn Camera Kit with built-in 4G for live transmission, WiFi for uploading, and GPS for live tracking. Features front and back dual cameras, hot-swappable battery, and up to 256GB storage.",
    highlights: ["2K Resolution Recording", "2.4 inch Touch Screen", "Built-in 4G + WiFi + GPS", "Front & Back Dual Cameras", "Hot-swappable Battery", "128GB Built-in Storage"],
    specs: [
      { label: "Model", value: "CP-EBK-1073-K" },
      { label: "Resolution", value: "2K (2560 x 1440)" },
      { label: "Display", value: "2.4 inch Color Touch Screen" },
      { label: "Connectivity", value: "4G + WiFi" },
      { label: "Location", value: "Built-in GPS" },
      { label: "Camera", value: "Front + Back Dual" },
      { label: "Battery", value: "3050mAh Hot-swappable" },
      { label: "Storage", value: "Up to 256GB (128GB Standard)" }
    ],
    inBox: ["1x Body Camera", "1x Docking Station", "Power Adapter", "USB Cable", "User Manual"]
  },
  {
    id: 19,
    name: "CP-EBC-4413",
    brand: "CP Plus",
    category: "bodycam",
    tag: "Body Cam",
    tagColor: "#37474f",
    subtitle: "4MP Body Worn Camera – IP67, 12Hr, Night Vision",
    image: "bodycam_4mp.png",
    images: ["bodycam_4mp.png", "bodycam_kit.png", "docking_station.png"],
    shortDesc: "4MP Body Camera — 1440P, 58MP Photo, 120° wide, 10m night vision, IP67.",
    description: "Rugged 4MP body worn camera with 2560x1440P recording, 58MP photo capture, 120° wide angle, and 10m night vision. IP67 rated with 12 hours continuous recording and auto-overwrite function.",
    highlights: ["4MP – 2560x1440P", "58MP Photo Capture", "120° Wide Angle", "10m Night Vision", "IP67 Waterproof", "12 Hours Recording"],
    specs: [
      { label: "Model", value: "CP-EBC-4413" },
      { label: "Resolution", value: "2560 x 1440P (4MP)" },
      { label: "Photo", value: "58MP" },
      { label: "Angle", value: "120° Wide Angle" },
      { label: "Night Vision", value: "10 Metres IR" },
      { label: "Waterproof", value: "IP67" },
      { label: "Battery", value: "12 Hours @720P" },
      { label: "Storage", value: "MicroSD (Auto-overwrite)" }
    ],
    inBox: ["1x Body Camera", "Clip Mount", "USB Cable", "User Manual"]
  },
  {
    id: 20,
    name: "CP-DDS-N10",
    brand: "CP Plus",
    category: "bodycam",
    tag: "Docking",
    tagColor: "#37474f",
    subtitle: "10 Port Docking Station for Body Worn Cameras",
    image: "docking_station.png",
    images: ["docking_station.png", "bodycam_kit.png", "bodycam_4mp.png"],
    shortDesc: "10 Port Docking — Simultaneous charge + data transfer, MTBF 20000hrs.",
    description: "10-port docking station for CP Plus body worn cameras. Cabin-type dock design with 1A-1.5A charging and USB 2.0 HUB for 400MB/min data transfer. Ideal for fleet management.",
    highlights: ["10 Port Simultaneous Charging", "1A-1.5A with Protection", "USB 2.0 HUB – 400MB/min", "MTBF ≥ 20,000 Hours", "Cabin Type Design", "Fleet Management Ready"],
    specs: [
      { label: "Model", value: "CP-DDS-N10" },
      { label: "Ports", value: "10 Port" },
      { label: "Charging", value: "1A – 1.5A with Protection" },
      { label: "Data Transfer", value: "USB 2.0, ≥400MB/min" },
      { label: "Reliability", value: "MTBF ≥ 20,000 Hours" }
    ],
    inBox: ["1x Docking Station", "Power Adapter", "USB Cable", "User Manual"]
  }

];

const FEATURED_IDS = [1, 2, 6, 7];
